Move serializer to where it should be
GeyserMC/Protocol pull request #6
Opened 2021-06-11 22:21 UTC by D3ATHBRINGER13

2021-06-18 16:51 UTC, D3ATHBRINGER13 commented
@RednedEpic I think this is all I'll be doing for a bit, so this is ready for review now :+1:

2021-06-20 18:05 UTC, RednedEpic requested changes

2021-06-20 18:05 UTC, RednedEpic commented on java/java-common/src/main/java/org/cloudburstmc/protocol/java/packet/play/clientbound/SetPlayerTeamPacket.java
> +    public enum TeamColor {
This can be entirely replaced with `NamedTextColor` and `TextDecoration` inside of adventure.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/SetObjectiveSerializer_v754.java
> +        if (packet.getAction().ordinal() == 0 || packet.getAction().ordinal() == 2) {
Don't use ordinal values here - just check for the action itself.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/SetObjectiveSerializer_v754.java
> +        if (action == 0 || action == 2) {
Same as above.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/SetPassengersSerializer_v754.java
> +        helper.writeVarInt(buffer, packet.getPassengerIds().length);
There is a `writeArray` method in JavaPacketHelper which allows you to write this much easier.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/SetPassengersSerializer_v754.java
> +        int[] passengerIds = new int[helper.readVarInt(buffer)];
Same as above, except with `readArray`.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/TeleportEntitySerializer_v754.java
> +        buffer.writeDouble(packet.getPosition().getZ());
Replace with `helper.writePosition`.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/TeleportEntitySerializer_v754.java
> +        buffer.writeByte((byte) (packet.getRotation().getY() * 256 / 300));
Replace with `helper.writeRotation2f`.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/TeleportEntitySerializer_v754.java
> +        ));
Replace with `helper.readPosition`.

2021-06-20 18:05 UTC, RednedEpic commented on java/java-v754/src/main/java/org/cloudburstmc/protocol/java/v754/serializer/play/clientbound/TeleportEntitySerializer_v754.java
> +        ));
Replace with `helper.readRotation2f`.

2021-06-25 20:02 UTC, RednedEpic approved these changes

2021-06-25 20:02 UTC, merged